version: '3.8'

services:

  #app:
  #  container_name: store-app
  #  build: .
  #  ports:
  #    - '8080:8080'
  #  depends_on:
  #     - postgres
  #  networks:
  #    - app-network


  postgres:
    container_name: store-database
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=storedb
      - POSTGRES_USER=superUser
      - POSTGRES_PASSWORD=secret
    ports:
      - '3000:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  #minio:
  #  image: docker.io/bitnami/minio:2024
  #  ports:
  #    - '9000:9000'
  #    - '9001:9001'
  #  networks:
  #    - minionetwork
  #  volumes:
  #    - minio_data:/data
  #  environment:
  #    - MINIO_ROOT_USER=admin
  #   - MINIO_ROOT_PASSWORD=password
  #    - MINIO_DEFAULT_BUCKETS=store-files

#networks:
#  minionetwork:
#    driver: bridge

#volumes:
#  minio_data:
#    driver: local